
package fr.smabtp.yca.controller.ws.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.4
 * 2015-11-18T17:27:07.625+01:00
 * Generated source version: 2.4.4
 */

@WebFault(name = "operationFault", targetNamespace = "http://smabtp.fr/service/souscription/ycaService/1.0")
public class OperationFault_Exception extends Exception {
    
    private fr.smabtp.yca.controller.ws.soap.OperationFault operationFault;

    public OperationFault_Exception() {
        super();
    }
    
    public OperationFault_Exception(String message) {
        super(message);
    }
    
    public OperationFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public OperationFault_Exception(String message, fr.smabtp.yca.controller.ws.soap.OperationFault operationFault) {
        super(message);
        this.operationFault = operationFault;
    }

    public OperationFault_Exception(String message, fr.smabtp.yca.controller.ws.soap.OperationFault operationFault, Throwable cause) {
        super(message, cause);
        this.operationFault = operationFault;
    }

    public fr.smabtp.yca.controller.ws.soap.OperationFault getFaultInfo() {
        return this.operationFault;
    }
}
